name: Validate Plugin Tested Up To Version
description: A GitHub action that validates the last tested plugin version against the current version of WordPress.
author: jazzsequence
branding:
  icon: file-plus
  color: orange
inputs:
  plugin-path:
    description: 'The path to the plugin to validate.'
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Validate Plugin Tested Up To Version
      shell: bash
      env:
        PLUGIN_PATH: ${{ inputs.plugin-path }}
      run: bash bin/validate-plugin-version.sh ${{ inputs.plugin-path }}
    # - name: Create Pull Request
      # if: # something here
      # Create a pull request with the changes made from running the script.
    