name: Validate Plugin Tested Up To Version
description: A GitHub action that validates the last tested plugin version against the current version of WordPress.
author: jazzsequence
branding:
  icon: file-plus
  color: orange
inputs:
  plugin-path:
    description: The path to the plugin to validate.
    required: false
    default: '.'
  dry-run:
    description: Whether to actually commit the changes to the repository.
    required: false
    default: false
  gh-token:
    description: The GitHub token to use for creating a pull request.
    required: false
    default: ${{ github.token }}
  filenames:
    description: The filenames to check for the tested up to version. Default is 'readme.txt,README.md'.
    required: false
    default: 'readme.txt,README.md'
  branch:
    description: The branch to use as the base for PRs and commit the changes back to.
    required: false
  pr-status:
    description: The status of the PR to create. Default is 'draft'. Accepts 'draft' or 'open'.
    required: false
    default: 'draft'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: Debug Action Environment
      shell: bash
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of action directory (looking for bin/validate-plugin-version.sh):"
        ls -R    
    - name: Validate Plugin Tested Up To Version
      shell: bash
      env:
        PLUGIN_PATH: ${{ inputs.plugin-path }}
        DRY_RUN: ${{ inputs.dry-run }}
        WORKFLOW_PATH: ${{ github.workspace }}
        GH_TOKEN: ${{ inputs.gh-token }}
        FILENAMES: ${{ inputs.filenames }}
        BRANCH: ${{ inputs.branch }}
        PR_STATUS: ${{ inputs.pr-status }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
      run: bash ${{ github.action_path }}/bin/validate-plugin-version.sh
    