name: Validate Plugin Version Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Plugin Version
        uses: ./
        with:
            plugin-path: '.github/workflows/fixtures/plugin-test/'