name: Validate Plugin Version Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Plugin Version
        uses: ./
        with:
            plugin-path: '.github/workflows/fixtures/plugin-test/'
            dry-run: true